apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wm36fjpxl-python 
  janus-idp.io/tekton: wm36fjpxl-python
  backstage.io/kubernetes-id: wm36fjpxl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wm36fjpxl-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  