apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: wm36fjpxl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wm36fjpxl-python 
  name: wm36fjpxl-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: wm36fjpxl-python
    weight: 100 
